/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check service health */
        get: operations["getServiceHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the ticket queue
         * @description Returns up to 50 tickets ordered by priority and SLA risk.
         */
        get: operations["listTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a complete ticket
         * @description Returns the conversation, customer context, approved sources, and current grounded draft for one ticket.
         */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            status: "ok";
            /** @constant */
            service: "relaydesk-web";
            /** Format: date-time */
            timestamp: string;
        };
        Customer: {
            id: string;
            name: string;
            email: string;
            company: string;
            /** @enum {string} */
            plan: "Enterprise" | "Scale" | "Growth" | "Starter";
            initials: string;
            since: string;
            timezone: string;
            /** @enum {string} */
            health: "healthy" | "watch" | "risk";
            lifetimeValue: string;
        };
        Message: {
            id: string;
            author: string;
            /** @enum {string} */
            role: "customer" | "agent" | "system";
            body: string;
            timestamp: string;
        };
        KnowledgeSource: {
            id: string;
            title: string;
            section: string;
            relevance: number;
        };
        Ticket: {
            id: string;
            subject: string;
            preview: string;
            customer: components["schemas"]["Customer"];
            /** @enum {string} */
            priority: "urgent" | "high" | "normal" | "low";
            /** @enum {string} */
            status: "open" | "pending" | "resolved";
            /** @enum {string} */
            channel: "email" | "chat" | "api";
            assignee: string | null;
            updatedAt: string;
            waitingMinutes: number;
            slaMinutes: number;
            tags: string[];
            intent: string;
            /** @enum {string} */
            sentiment: "positive" | "neutral" | "frustrated";
            summary: string;
            messages: components["schemas"]["Message"][];
            sources: components["schemas"]["KnowledgeSource"][];
            suggestedReply: string;
            detailsLoaded?: boolean;
        };
        QueueSummary: {
            all: number;
            mine: number;
            unassigned: number;
            urgent: number;
        };
        TicketListMeta: {
            query: string;
            /** @enum {string} */
            filter: "all" | "mine" | "unassigned" | "urgent";
            returned: number;
            summary: components["schemas"]["QueueSummary"];
        };
        TicketListResponse: {
            data: components["schemas"]["Ticket"][];
            meta: components["schemas"]["TicketListMeta"];
        };
        TicketDetailResponse: {
            data: components["schemas"]["Ticket"];
        };
        ErrorResponse: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getServiceHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RelayDesk is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listTickets: {
        parameters: {
            query?: {
                /** @description Full-text search across ticket and customer fields. */
                q?: string;
                /** @description Queue segment to return. */
                filter?: "all" | "mine" | "unassigned" | "urgent";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching queue projection and queue summary. */
            200: {
                headers: {
                    /** @description Repository read duration. */
                    "Server-Timing"?: string;
                    /** @description Repository that served the response. */
                    "X-RelayDesk-Data-Source"?: "postgres" | "synthetic-fallback";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description RelayDesk ticket identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The complete ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailResponse"];
                };
            };
            /** @description No ticket has the requested identifier. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
