import type { Ticket } from "@/lib/types";

export const tickets: Ticket[] = [
  {
    id: "RD-1842",
    subject: "SSO domain verification is stuck",
    preview: "We added the TXT record yesterday, but the admin screen still says pending.",
    customer: {
      id: "cus_atlas",
      name: "Maya Chen",
      email: "maya@atlashealth.io",
      company: "Atlas Health",
      plan: "Enterprise",
      initials: "MC",
      since: "Mar 2024",
      timezone: "San Francisco, 8:42 AM",
      health: "watch",
      lifetimeValue: "$48,600",
    },
    priority: "urgent",
    status: "open",
    channel: "email",
    assignee: null,
    updatedAt: "4 min",
    waitingMinutes: 42,
    slaMinutes: 60,
    tags: ["sso", "enterprise", "onboarding"],
    intent: "Identity setup",
    sentiment: "frustrated",
    summary:
      "Atlas Health is blocked during enterprise onboarding. Their DNS record appears valid, but verification has not completed after 18 hours.",
    messages: [
      {
        id: "msg_1842_1",
        author: "Maya Chen",
        role: "customer",
        timestamp: "Today, 8:18 AM",
        body: "Hi team, we added the TXT record your setup screen provided yesterday. Our DNS checker can see it, but RelayDesk still shows the domain as pending. We have 120 agents waiting to sign in for training this afternoon. Can you help us unblock this?",
      },
      {
        id: "msg_1842_2",
        author: "RelayDesk",
        role: "system",
        timestamp: "Today, 8:19 AM",
        body: "Intent detected: Identity setup. SLA policy: Enterprise onboarding, 60 minute first response.",
      },
    ],
    sources: [
      {
        id: "kb_14",
        title: "Verify a domain for SSO",
        section: "Troubleshooting DNS propagation",
        relevance: 96,
      },
      {
        id: "runbook_6",
        title: "Identity provider escalation runbook",
        section: "Manual verification criteria",
        relevance: 88,
      },
    ],
    suggestedReply:
      "Hi Maya, I checked the verification request for atlashealth.io. The TXT record is resolving correctly, but the original verification job did not retry after DNS propagation completed. I have restarted that check and the domain should move to Verified within five minutes. You do not need to change the record. I will stay on this ticket and confirm before your agent training begins.",
  },
  {
    id: "RD-1839",
    subject: "Usage export is missing July events",
    preview: "Our finance team sees a gap between July 12 and July 16 in the CSV export.",
    customer: {
      id: "cus_northline",
      name: "Jon Bell",
      email: "jon@northline.dev",
      company: "Northline",
      plan: "Scale",
      initials: "JB",
      since: "Nov 2024",
      timezone: "New York, 11:42 AM",
      health: "healthy",
      lifetimeValue: "$19,200",
    },
    priority: "high",
    status: "open",
    channel: "chat",
    assignee: "You",
    updatedAt: "12 min",
    waitingMinutes: 31,
    slaMinutes: 120,
    tags: ["exports", "billing"],
    intent: "Data export",
    sentiment: "neutral",
    summary:
      "Northline reports a four-day gap in its July usage CSV. The in-product dashboard includes the events, suggesting an export pagination issue.",
    messages: [
      {
        id: "msg_1839_1",
        author: "Jon Bell",
        role: "customer",
        timestamp: "Today, 11:11 AM",
        body: "Our finance team downloaded the July usage export and noticed there are no events from July 12 through July 16. The dashboard totals look right. Could this be an export issue?",
      },
    ],
    sources: [
      {
        id: "kb_22",
        title: "Export usage and billing data",
        section: "Large exports",
        relevance: 92,
      },
    ],
    suggestedReply:
      "Hi Jon, thanks for flagging this. Your usage data is intact, but I can reproduce a pagination gap in the CSV export for that date range. I have generated a complete replacement export and attached it here. Our engineering team is correcting the exporter so future downloads include every page automatically.",
  },
  {
    id: "RD-1836",
    subject: "Can we restrict AI suggestions by team?",
    preview: "Our legal queue should use a different set of approved sources.",
    customer: {
      id: "cus_finch",
      name: "Priya Raman",
      email: "priya@finchlegal.com",
      company: "Finch Legal",
      plan: "Enterprise",
      initials: "PR",
      since: "Jan 2025",
      timezone: "London, 4:42 PM",
      health: "healthy",
      lifetimeValue: "$61,400",
    },
    priority: "normal",
    status: "open",
    channel: "email",
    assignee: "Sam R.",
    updatedAt: "27 min",
    waitingMinutes: 55,
    slaMinutes: 240,
    tags: ["ai", "permissions"],
    intent: "Product capability",
    sentiment: "positive",
    summary:
      "Finch Legal wants its legal queue to ground AI suggestions only in documents approved for that team.",
    messages: [
      {
        id: "msg_1836_1",
        author: "Priya Raman",
        role: "customer",
        timestamp: "Today, 4:15 PM",
        body: "We love the suggested replies. Can we configure the legal support queue to use only the policies that our compliance team has approved? Other teams can keep using the full knowledge base.",
      },
    ],
    sources: [
      {
        id: "kb_31",
        title: "Control AI knowledge sources",
        section: "Collection permissions",
        relevance: 94,
      },
    ],
    suggestedReply:
      "Hi Priya, yes. Create a Legal collection, add the approved policies, and grant that collection to the Legal queue. Suggestions in that queue will cite only those sources. Workspace administrators can still audit which articles supported each draft.",
  },
  {
    id: "RD-1831",
    subject: "Webhook deliveries are being retried",
    preview: "We acknowledge within 200 ms, but events still arrive three or four times.",
    customer: {
      id: "cus_kite",
      name: "Theo Martin",
      email: "theo@kitepay.co",
      company: "KitePay",
      plan: "Scale",
      initials: "TM",
      since: "Aug 2025",
      timezone: "Paris, 5:42 PM",
      health: "risk",
      lifetimeValue: "$24,000",
    },
    priority: "high",
    status: "pending",
    channel: "api",
    assignee: "You",
    updatedAt: "46 min",
    waitingMinutes: 8,
    slaMinutes: 120,
    tags: ["api", "webhooks", "developer"],
    intent: "Integration reliability",
    sentiment: "frustrated",
    summary:
      "KitePay receives duplicate ticket.updated webhooks despite fast acknowledgements. Delivery logs show intermittent timeout classification.",
    messages: [
      {
        id: "msg_1831_1",
        author: "Theo Martin",
        role: "customer",
        timestamp: "Today, 4:48 PM",
        body: "We are seeing ticket.updated events delivered three or four times. Our endpoint returns 200 in under 200 ms. Request IDs available if your team needs them.",
      },
      {
        id: "msg_1831_2",
        author: "Arun S.",
        role: "agent",
        timestamp: "Today, 5:04 PM",
        body: "Thanks Theo. I found the affected delivery group and asked our platform team to inspect the retry classification. I will update you when we have the trace.",
      },
    ],
    sources: [
      {
        id: "kb_42",
        title: "Webhook delivery and retries",
        section: "Idempotency and delivery IDs",
        relevance: 91,
      },
      {
        id: "runbook_11",
        title: "Webhook delivery investigation",
        section: "Duplicate delivery checklist",
        relevance: 84,
      },
    ],
    suggestedReply:
      "Hi Theo, we found the affected delivery group. Your endpoint responses were successful, but our worker recorded two acknowledgements after the retry lease had already renewed. We have stopped the duplicate deliveries and are deploying a lease-handling fix. Continue deduplicating on the delivery ID as documented, and I will confirm after the deployment completes.",
  },
  {
    id: "RD-1827",
    subject: "Invite link opens the wrong workspace",
    preview: "The link sends new teammates into our sandbox instead of production.",
    customer: {
      id: "cus_sundial",
      name: "Elena Ortiz",
      email: "elena@sundial.energy",
      company: "Sundial Energy",
      plan: "Growth",
      initials: "EO",
      since: "Apr 2025",
      timezone: "Austin, 10:42 AM",
      health: "watch",
      lifetimeValue: "$9,600",
    },
    priority: "normal",
    status: "open",
    channel: "email",
    assignee: null,
    updatedAt: "1 hr",
    waitingMinutes: 64,
    slaMinutes: 240,
    tags: ["workspace", "invites"],
    intent: "Account administration",
    sentiment: "neutral",
    summary:
      "Sundial Energy copied an invitation from its sandbox workspace while intending to onboard users to production.",
    messages: [
      {
        id: "msg_1827_1",
        author: "Elena Ortiz",
        role: "customer",
        timestamp: "Today, 9:38 AM",
        body: "Our latest invite link keeps placing teammates in the Sundial Sandbox workspace. We need them in Sundial Production. Is the workspace encoded into the link?",
      },
    ],
    sources: [
      {
        id: "kb_8",
        title: "Invite teammates to a workspace",
        section: "Workspace-specific invitations",
        relevance: 97,
      },
    ],
    suggestedReply:
      "Hi Elena, the workspace is encoded into each invitation link. The link you shared was created from Sundial Sandbox. Switch to Sundial Production, open Settings, then Members, and create a new invitation. I have also invalidated the unused sandbox invitations so nobody joins the wrong workspace.",
  },
  {
    id: "RD-1819",
    subject: "Resolved conversations reappear after import",
    preview: "An overnight import reopened 38 tickets that were already closed.",
    customer: {
      id: "cus_morrow",
      name: "Drew Foster",
      email: "drew@morrowgoods.com",
      company: "Morrow Goods",
      plan: "Growth",
      initials: "DF",
      since: "Sep 2024",
      timezone: "Toronto, 11:42 AM",
      health: "watch",
      lifetimeValue: "$11,800",
    },
    priority: "high",
    status: "open",
    channel: "api",
    assignee: "Lina K.",
    updatedAt: "2 hr",
    waitingMinutes: 102,
    slaMinutes: 180,
    tags: ["import", "status"],
    intent: "Data migration",
    sentiment: "frustrated",
    summary:
      "A scheduled import reopened 38 resolved conversations because the source system omitted a status value on unchanged records.",
    messages: [
      {
        id: "msg_1819_1",
        author: "Drew Foster",
        role: "customer",
        timestamp: "Today, 9:58 AM",
        body: "Our overnight import reopened 38 conversations that had already been resolved. Agents are seeing them in the queue again. We have paused the importer for now.",
      },
    ],
    sources: [
      {
        id: "kb_37",
        title: "Import historical conversations",
        section: "Status precedence",
        relevance: 89,
      },
    ],
    suggestedReply:
      "Hi Drew, pausing the importer was the right call. I found that records without an explicit source status were treated as open instead of preserving their existing RelayDesk status. We have restored the 38 conversations to resolved and prepared a correction for the importer. I will let you know when it is safe to resume the schedule.",
  },
  {
    id: "RD-1808",
    subject: "Thanks for the migration help",
    preview: "Everything looks good after moving our knowledge base.",
    customer: {
      id: "cus_archer",
      name: "Noah Williams",
      email: "noah@archer.studio",
      company: "Archer Studio",
      plan: "Starter",
      initials: "NW",
      since: "Jun 2026",
      timezone: "Melbourne, 1:42 AM",
      health: "healthy",
      lifetimeValue: "$1,440",
    },
    priority: "low",
    status: "resolved",
    channel: "chat",
    assignee: "You",
    updatedAt: "Yesterday",
    waitingMinutes: 0,
    slaMinutes: 480,
    tags: ["migration", "knowledge"],
    intent: "Migration confirmation",
    sentiment: "positive",
    summary:
      "Archer Studio confirmed that its knowledge-base migration completed successfully and article links work as expected.",
    messages: [
      {
        id: "msg_1808_1",
        author: "Noah Williams",
        role: "customer",
        timestamp: "Yesterday, 3:12 PM",
        body: "Everything looks great after the migration. The redirects are working and our team can find all the old articles. Thanks for guiding us through it.",
      },
      {
        id: "msg_1808_2",
        author: "Arun S.",
        role: "agent",
        timestamp: "Yesterday, 3:20 PM",
        body: "Great to hear, Noah. I have marked the migration complete. If you spot anything unusual in the next few days, reply here and the conversation will reopen.",
      },
    ],
    sources: [],
    suggestedReply: "",
  },
];
